client_config_backend: settings
client_config:
  client_id: 477272973618-75b5et736ji8qep1slqgfath32eddo9p.apps.googleusercontent.com
  client_secret: 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
save_credentials_backend: file
save_credentials_file: credentials.json
get_refresh_token: True
oauth_scope:
  - https://www.googleapis.com/auth/drive.file